# Generated by Django 5.2.13 on 2026-05-06 20:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AiApiKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "label",
                    models.TextField(
                        help_text="Human-friendly name, e.g. 'Production'."
                    ),
                ),
                (
                    "provider",
                    models.TextField(
                        choices=[("groq", "Groq"), ("gemini", "Google Gemini")],
                        default="groq",
                    ),
                ),
                ("api_key", models.TextField()),
                ("model_name", models.TextField(default="llama-3.3-70b-versatile")),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI API Key",
                "verbose_name_plural": "AI API Keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AiSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.TextField(
                        choices=[("gemini", "Google Gemini")], default="gemini"
                    ),
                ),
                ("api_key", models.TextField(blank=True, default="")),
                ("model_name", models.TextField(default="gemini-2.0-flash")),
                ("assistant_name", models.TextField(default="Aria")),
                (
                    "welcome_message",
                    models.TextField(
                        default="Hi 👋  I'm Aria — Moreadorn's trade assistant. Ask me about our products, shipping destinations, or compliance."
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("max_output_tokens", models.IntegerField(default=800)),
                ("temperature", models.FloatField(default=0.4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Settings",
                "verbose_name_plural": "AI Settings",
            },
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.TextField()),
                ("slug", models.TextField(blank=True, default="", unique=True)),
                ("excerpt", models.TextField()),
                ("body", models.TextField()),
                ("author", models.TextField(default="moreAdorn")),
                ("tags", models.TextField(blank=True, default="")),
                ("images", models.JSONField(blank=True, default=list)),
                ("videos", models.JSONField(blank=True, default=list)),
                ("published", models.BooleanField(default=False)),
                ("publish_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-publish_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompanyContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query_email", models.TextField(blank=True, default="")),
                ("contact_email", models.TextField(blank=True, default="")),
                ("phone", models.TextField(blank=True, default="")),
                ("address", models.TextField(blank=True, default="")),
                ("city", models.TextField(blank=True, default="")),
                ("state", models.TextField(blank=True, default="")),
                ("country", models.TextField(blank=True, default="")),
                ("zip_code", models.TextField(blank=True, default="")),
                ("google_maps_url", models.TextField(blank=True, default="")),
                ("business_hours", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company Contact",
                "verbose_name_plural": "Company Contact",
            },
        ),
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("country", models.TextField(unique=True)),
                (
                    "code",
                    models.TextField(
                        help_text="3-letter ISO country code (e.g. USA, GBR).",
                        unique=True,
                    ),
                ),
                ("flag", models.TextField(help_text="Flag emoji.")),
                (
                    "region",
                    models.TextField(
                        choices=[
                            ("north_america", "North America"),
                            ("europe", "Europe"),
                            ("middle_east", "Middle East"),
                            ("east_asia", "East Asia"),
                            ("southeast_asia", "Southeast Asia"),
                            ("south_asia", "South Asia"),
                            ("africa", "Africa"),
                            ("oceania", "Oceania"),
                            ("south_america", "South America"),
                            ("central_america", "Central America"),
                        ]
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                (
                    "description",
                    models.TextField(
                        help_text="Short description shown on the product card."
                    ),
                ),
                ("details", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.TextField(
                        choices=[
                            ("textiles", "Textiles & Fabrics"),
                            ("electronics", "Electronics & Components"),
                            ("machinery", "Industrial Machinery"),
                            ("consumer", "Consumer Goods"),
                            ("automotive", "Automotive Parts"),
                            ("construction", "Construction Materials"),
                            ("food", "Food & Beverages"),
                            ("medical", "Medical Supplies"),
                            ("sports", "Sports & Fitness"),
                            ("furniture", "Furniture & Furnishings"),
                            ("chemicals", "Chemicals & Raw Materials"),
                            ("agricultural", "Agricultural Products"),
                            ("other", "Other"),
                        ]
                    ),
                ),
                ("tags", models.TextField(blank=True, default="")),
                ("moq", models.TextField(blank=True, default="", verbose_name="MOQ")),
                ("lead_time", models.TextField(blank=True, default="")),
                ("images", models.JSONField(blank=True, default=list)),
                ("videos", models.JSONField(blank=True, default=list)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("facebook_url", models.TextField(blank=True, default="")),
                ("instagram_url", models.TextField(blank=True, default="")),
                ("linkedin_url", models.TextField(blank=True, default="")),
                ("twitter_url", models.TextField(blank=True, default="")),
                ("youtube_url", models.TextField(blank=True, default="")),
                ("whatsapp_url", models.TextField(blank=True, default="")),
                ("telegram_url", models.TextField(blank=True, default="")),
                ("pinterest_url", models.TextField(blank=True, default="")),
                ("github_url", models.TextField(blank=True, default="")),
                ("website_url", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Social Media",
                "verbose_name_plural": "Social Media",
            },
        ),
        migrations.CreateModel(
            name="RequestQuote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category_name",
                    models.TextField(
                        choices=[
                            ("product", "Product"),
                            ("contact", "ContactUs"),
                            ("info", "RequestInfoQuote"),
                        ],
                        default="product",
                    ),
                ),
                ("product_name", models.TextField(blank=True, default="")),
                ("quantity", models.TextField(blank=True, default="")),
                ("name", models.TextField()),
                ("whatsapp", models.TextField(blank=True, default="")),
                ("phone", models.TextField(blank=True, default="")),
                ("email", models.TextField()),
                ("country", models.TextField(blank=True, default="")),
                ("city", models.TextField(blank=True, default="")),
                ("state", models.TextField(blank=True, default="")),
                ("zip_code", models.TextField(blank=True, default="")),
                ("address", models.TextField(blank=True, default="")),
                ("description", models.TextField()),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("quoted", "Quoted"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                    ),
                ),
                ("admin_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_requests",
                        to="moreadornexportapp.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Request Quote",
                "verbose_name_plural": "Request Quotes",
                "ordering": ["-created_at"],
            },
        ),
    ]
